config/routes.rb
Rails.application.routes.draw do

  #active admin
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  match "/admin/admin_users/import_admin_users" => 'admin/admin_users#import_admin_users', via: [:get, :post]
  match "/admin/articles/import_articles" => 'admin/articles#import_articles', via: [:get, :post]
  match "/admin/average_prices/import_average_prices" => 'admin/average_prices#import_average_prices', via: [:get, :post]
  match "/admin/categories/import_categories" => 'admin/categories#import_categories', via: [:get, :post]
  match "/admin/dispensaries/import_dispensaries" => 'admin/dispensaries#import_dispensaries', via: [:get, :post]
  match "/admin/products/import_products" => 'admin/products#import_products', via: [:get, :post]
  
  match "/admin/dispensary_sources/:id/add_to_store" => 'admin/dispensary_sources#add_to_store', via: :post
  match "/admin/dispensary_sources/:id/delete_from_store" => 'admin/dispensary_sources#delete_from_store', via: :post
  match "/admin/dispensary_sources/:id/update_product_store" => 'admin/dispensary_sources#update_product_store', via: :put
  match "/admin/dispensary_source_products/add_to_store" => 'admin/dispensary_source_products#add_to_store', via: :post
  match "/admin/dispensary_products/add_to_store" => 'admin/dispensary_products#add_to_store', via: [:post, :patch]
  
  #ecommerce
  resources :carts
  resources :product_items
  get 'add_to_cart/:product_id/:dispensary_source_id', to: 'product_items#add_to_cart', :as => :add_to_cart
  resources :orders
  
  #SIDEKIQ Routes
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => "/background"

  #GENERAL PAGES
  root 'pages#home'

  get 'admin', to: 'pages#admin'
  get 'search', to: 'pages#search'
  get 'save_email', to: 'pages#save_email'
  get 'unsubscribe', to: 'pages#unsubscribe'
  
  get 'contact_us', to: 'pages#contact_us'
  get 'submit_contact_form', to: 'pages#submit_contact_form'
  
  get 'feedback', to: 'pages#feedback'
  get 'submit_feedback_form', to: 'pages#submit_feedback_form'
  
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms_conditions', to: 'pages#terms_conditions'
  get 'about', to: 'pages#about'
  
  #sitemap
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  
  #DIFF STYLING
  get 'test', to: 'diff_layouts#test'
  
  #LOGIN AND LOGOUT
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #USER
  get 'signup', to: 'users#new'
  resources :users, except: [:new] do 
    collection do
      delete 'destroy_multiple'
    end
  end
  get 'users-admin', to: 'users#admin'
  get 'change_password/:id', to: 'users#change_password', as: 'change_password'
  get 'submit_password_change', to: 'users#submit_password_change' 
  
  put 'user_source_save/:source_id', to: 'users#user_source_save', as: 'user_source_save'
  put 'user_category_save/:category_id', to: 'users#user_category_save', as: 'user_category_save'
  put 'user_state_save/:state_id', to: 'users#user_state_save', as: 'user_state_save'
  
  #RESET PASSWORD
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  #ERROR FILES
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'errors/application_error'
  
  #ERROR HANDLING
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/503", :to => "errors#application_error", :via => :all
  
  resources :blog
  resources :categories
  resources :sources
  resources :average_prices
  resources :vendor_products
  resources :dispensary_sources
  resources :dispensary_source_products
  resources :dsp_prices
  resources :dispensary_products

  #ARTICLES
  resources :articles
  get 'digest', to: 'articles#digest'
  get 'send_weekly_digest', to: 'articles#send_weekly_digest'
  get 'tweet/:id', to: 'articles#tweet', as: 'tweet'
  put 'save_visit/:id', to: 'articles#save_visit', as: 'save_visit'
  put 'user_article_save/:id', to: 'articles#user_article_save', as: 'user_article_save'
  get 'send_tweet', to: 'articles#send_tweet'
  get 'update_states_categories', to: 'articles#update_states_categories'
  get 'update_article_tags', to: 'articles#update_article_tags'
  
  #PRODUCTS
  resources :products
  post "products_refine_index", to: "products#refine_index"
  get "products_refine_index", to: "products#refine_index"
  post 'products/:id/change_state' => 'products#change_state', as: 'change_state_product'
  
  #STATES
  resources :states
  post 'states/:id/refine_products' => 'states#refine_products', as: 'refine_state_products'

  #VENDORS
  resources :vendors
  post 'vendors/refine_index' => 'vendors#refine_index', as: 'refine_vendor_index'

  #DISPENSARIES
  resources :dispensaries
  post 'dispensaries/refine_index' => 'dispensaries#refine_index', as: 'refine_dispensary_index'

end

app/views/shared/_average_price_vendor.html.erb
<div class="product-info">
    <p style="max-height: 53px; overflow: hidden;">Produced By:
        <% product.vendors.each_with_index do |vendor, index| %>
            <% if index + 1 == product.vendors.size %>
                <%= link_to vendor.name, vendor_path(vendor), :class => 'vendor_path'%>
            <% else %>
                <%= link_to vendor.name, vendor_path(vendor), :class => 'vendor_path'%>,&nbsp;
            <% end %>
        <% end %>
    </p>
</div>
<div class="product-info">
    <p>Average Prices:
        <% product.average_prices.each_with_index do |average_price, index| %>
            <% if index + 1 == product.average_prices.size %>
                <a href="<%=product_path(product, average_price_id: average_price.id)%>" style="color: #2ab081;">
                    <%="$#{average_price.average_price.round}/#{average_price.average_price_unit}"%></a>
            <% else %>
                <a href="<%=product_path(product, average_price_id: average_price.id)%>" style="color: #2ab081;">
                    <%="$#{average_price.average_price.round}/#{average_price.average_price_unit}"%></a>,&nbsp;
            <% end %>
        <% end %>
    </p>
</div>

app/views/shared/_dropdown_az.html.erb
<select name="AZ" class="selectDropdown az-dropdown" data-live-search="true" onChange="selectSelectedAZValue(this.value)">
    <option value = ''>A-Z Filter</option>
    <% @az_values.each do |letter| %>
    	<% if @az_letter != nil && @az_letter == letter %>
    		<option value = "<%=letter%>" selected="selected"><%=letter%></option>
    	<% else %>
    		<option value = "<%=letter%>"><%=letter%></option>
    	<% end %>
    <% end %>
</select>

app/views/shared/_dropdown_categories.html.erb
<select name="Category" class="selectDropdown category-dropdown" data-live-search="true" onChange="setSelectedCategory(this.value)">
    <option value = "">Category</option>
    <% @product_categories.each do |category| %>
    
        <% if @searched_category != nil && @searched_category.name == category.name%>
            <option value = "<%=category.name%>" selected="selected"><%=category.name%></option>
        <% else %>
        	<option value = "<%=category.name%>"><%=category.name%></option>
        <% end %>
        
        <% if category.name == 'Flower' %>
            <!--add in others-->
            <option value="Indica">&nbsp&nbsp&nbsp&nbspIndica</option>
            <option value="Sativa">&nbsp&nbsp&nbsp&nbspSativa</option>
            <option value="Hybrid">&nbsp&nbsp&nbsp&nbspHybrid</option>
            <option value="Hybrid-Indica">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspHybrid-Indica</option>
            <option value="Hybrid-Sativa">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspHybrid-Sativa</option>
        <% end %>

    <% end %>
</select>

app/views/shared/_dropdown_states.html.erb
<select name="State" class="selectDropdown state-dropdown" data-live-search="true" onChange="setSelectedState(this.value)">
    <option value = "">State</option>
    <% @states_with_products.each do |state| %>
        <% if @site_visitor_state != nil && @site_visitor_state.name == state.name && @searched_state == nil %>
            <option value = "<%=state.id%>" selected="selected"><%=state.name%></option>
            <% @set_state = state.name %>
        <% elsif @searched_state != nil && @searched_state.name == state.name%>
            <option value = "<%=state.id%>" selected="selected"><%=state.name%></option>
			<% @set_state = state.name %>
        <% elsif @state != nil && @state.name == state.name%>
            <option value = "<%=state.id%>" selected="selected"><%=state.name%></option>
            <% @set_state = state.name %>
        <% elsif @state != nil && @state.name == state.name%>
            <option value = "<%=state.id%>" selected="selected"><%=state.name%></option>
            <% @set_state = state.name %>
        <% else %>
        	<option value = "<%=state.id%>"><%=state.name%></option>
        <% end %>
    <% end %>
</select>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prevented this from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Start footer area -->
<footer id="footer" class="footer-wrapper footer-1">
    
    
    <!-- Start footer top area -->
    <div class="footer-top-wrap ptb-20 bg-dark">
        <div class="container">
            <div class="row">
                
                <div class="col-md-12">
                    <div class = 'footer-image'>
                        <% if Rails.env.production? %>
        				    <%= link_to image_tag("header_footer/cbz-logo-grayscale.PNG"), root_path %>
        			    <% end %>
        			</div>
        		</div>
                
            </div>
        </div>
    </div>
    <!-- End footer top area -->
    
    
    <div class="footer-buttom bg-black ptb-15">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
                    <div class="zm-copyright">
                        <p class="uppercase">&copy;<script>document.write(new Date().getFullYear())</script> CBZ Technologies Inc. All Rights Reserved.</p>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 text-right hidden-xs">
                    <nav class="footer-menu zm-secondary-menu text-right">
                        <ul>
                            <li><a href="<%=terms_conditions_path%>">Terms &amp; Conditions</a></li>
                            <li><a href="<%= privacy_policy_path %>">Privacy Policy</a></li>
                            <li><a href="<%= contact_us_path %>">Contact Us</a></li>
                            <li><a href="<%= feedback_path %>">Leave Feedback</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- End footer area -->

app/views/shared/_header.html.erb
<!-- Start of header area -->
<header  class="header-area header-wrapper clearfix" style="background-image: url('<%= asset_path 'header_footer/cbz_source_banner.png' %>'); background-size: 100%">
    <div class="header-top-bar bg-dark ptb-10">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-7 hidden-991">
                    <div class="header-top-left">
                        <nav class="header-top-menu zm-secondary-menu">
                            <ul>
                                <!--desktop logo-->
                                <% if @state.present? && @state.logo.present? %>
                                    <a href="<%=root_path%>">
                                        <img style ="margin-top: -10px" src="<%=asset_path(@state.logo)%>">
                                    </a>
                                <% elsif @site_visitor_state.present? %>
                                    <a href="<%=root_path%>">
                                        <img style ="margin-top: -10px" src="<%=asset_path(@site_visitor_state.logo)%>">
                                    </a>    
                                <% else %>
                            	    <%= link_to image_tag("header_footer/cbz-logo-color.svg"), root_path %>
                                <% end %>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-5">
                    <div class="header-top-right clierfix text-right">
                        <div class="user-accoint topbar-sblock">
                                <span class="login-btn uppercase">
                                    <%= link_to @cart, class: 'menu-cart' do  %>
        								<i class="fa fa-shopping-cart"></i>
        								<%= number_to_currency @cart.total_price %>
        							<% end %>
                                </span>
                                <span class="uppercase"> | </span>
                            <% if logged_in? %>
                                <span class="login-btn uppercase"><%= link_to 'Logout', logout_path, method: :delete %></span>
                                <span class="uppercase"> | </span>
                                <span class="login-btn uppercase"><%= link_to 'Change Password', change_password_path(current_user) %></span>
                            <% else %>
                                <span class="login-btn uppercase"><%= link_to 'Login', login_path %></span>
                                <span class="uppercase"> | </span>
                                <span class="login-btn uppercase"><%= link_to 'Register', signup_path %></span>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="header-middle-area">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-lg-4 col-xs-12 header-mdh">
                    <div class="global-table">
                        <div class="global-row">
                            <div class="global-cell">
                                <div class="logo">
                                    <!--if state use the state logo-->
                                    <% if @state != nil && @state.logo.present? %>
                                        <%= link_to image_tag(asset_path(@state.logo), alt: "#{@state.name} Cannabiz Logo"), root_path %>
                                    <% elsif @site_visitor_state != nil && @site_visitor_state.logo.present? %>
                                        <%= link_to image_tag(asset_path(@site_visitor_state.logo), alt: "#{@site_visitor_state.name} Cannabiz Logo"), root_path %>
                                    <% else %>
                                	    <%= link_to image_tag("header_footer/cbz-logo-color.svg", alt: "Cannabiz Network Logo"), root_path %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="header-bottom-area bg-theme hidden-sm hidden-xs">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="menu-wrapper clearfix">
                        <div class="row">
                            <div class="col-md-11">
                                <div class="mainmenu-area">
                                    <nav class="primary-menu uppercase">
                                        <ul class="clearfix customnavfont">
                                            <li><%= link_to 'Home', root_path %></li>
                                            <li>
                                                <% if current_user %>
                                                    <a href="<%= user_path(current_user)%>">My Page</a>
                                                <% else %>
                                                    <a href="<%= login_path %>">My Page</a>
                                                <% end %>
                                            </li>
                                            <% if @site_visitor_state.present? %>
                                                <li><a href="<%= state_path(@site_visitor_state) %>">News</a></li>
                                            <% else %>
                                                <li><a href="<%= articles_path %>">News</a></li>
                                            <% end %>
                                            
                                            <li><a href="<%= products_path %>">Products</a></li>
                                            <li><a href="<%= blog_index_path %>">Blog</a></li>
                                            <li class="ipad-remove"><a href="<%= contact_us_path %>">Contact Us</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-md-1" style="padding-right: 0;">
                                <div class="search-wrap pull-right">
                                    <div class="search-form">
                                        
                                        <form class="navbar-form" role="search" method="get" action = '/search'>
                                            <input type="search" name="query" placeholder="Search by Product, Not by Dispensary" autocomplete='on'>
                                            <button type="submit">Search</button>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- mobile-menu-area start -->
    <div class="mobile-menu-area hidden-md hidden-lg">
        <div class="fluid-container">
            <div class="mobile-menu clearfix">
                <div class="search-wrap mobile-search">
                    <div class="mobile-search-btn"><%=image_tag("icons/search.png")%></div>
                    <div class="mobile-search-form">
                        <form class="navbar-form" role="search" method="get" action = '/search'>
                            <input type="text" name="query" placeholder="Search by Product, not by Dispensary" autocomplete='on'>
                            <button type="submit"><%=image_tag("icons/search.png")%></button>
                        </form>
                    </div>
                </div>
                <nav id="mobile_dropdown">
                    <ul class="customnavfont">
                        
                        <li><%= link_to 'Home', root_path %></li>
                        <li>
                            <% if current_user %>
                                <a href="<%= user_path(current_user)%>">My Page</a>
                            <% else %>
                                <a href="<%= login_path %>">My Page</a>
                            <% end %>
                        </li>
                        <li><a href="<%= articles_path %>">News</a></li>
                        <li><a href="<%= products_path %>">Products</a></li>
                        <li><a href="<%= contact_us_path %>">Contact Us</a></li>
                        <li><a href="<%= feedback_path %>">Leave Feedback</a></li>
                                            
                    </ul>
                </nav>
            </div>       
        </div>
    </div>
    <!-- mobile-menu-area end -->   
</header>

<!--mobile sticky header-->
<div id = "mobile-sticky-logo">
    <!--desktop logo-->
    <% if @state.present? && @state.logo.present? %>
        <%= link_to image_tag(asset_path(@state.logo)), root_path %>
    <% elsif @site_visitor_state.present? && @site_visitor_state.logo.present? %>
        <%= link_to image_tag(asset_path(@site_visitor_state.logo)), root_path %>
    <% else %>
	    <%= link_to image_tag("header_footer/mean-bar-logo.png"), root_path %>
    <% end %>
</div>

<div id = "mobile-sticky-header">
    <div class="col-xs-12">
        <div class="archive-inner">
            <div class="archive-filter">
                <% if @recents.present? || @article.present? %>
                    <%= render 'shared/sticky_header_news' %>	                    
				<% elsif @products.present? || @product.present? %>
					<%= render 'shared/sticky_header_products' %>
				<% elsif @dispensary.present? && current_page?(dispensary_path(@dispensary)) %>
				    <%= render 'shared/sticky_header_dispensary' %>
				<% else %>
				    <%= render 'shared/sticky_header_home' %>
				<% end %>
            </div>
        </div>
    </div>                        
</div>

app/views/shared/_message.html.erb
<!--toastr-->
<% unless flash.empty? %>
  <script type="text/javascript">
	  <% flash.each do |f| %>
	    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
	    toastr['<%= type %>'] ('<%= f[1] %>')
	  <% end %>
	</script>
<% end %>

app/views/shared/_messages.html.erb
  <div class="flash-messages">
    <!--<div class="row">-->
      <!--<div class="col-xs-10 col-xs-offset-1">-->
        <% flash.each do |name, msg| %>
          <div class='alert alert-<%="#{name}" %>'>
              <a href="#" class="close" data-dismiss="alert">×</a>
              <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
          </div>
        <% end %>
      <!--</div>-->
    <!--</div>-->
  </div>

app/views/shared/_msg.html.erb
<% unless @order.errors.empty? %>
  <script type="text/javascript">
	  <% @order.errors.full_messages.each do |msg| %>
	    toastr.error('<%= msg %>')
	  <% end %>
	</script>
<% end %>

app/views/shared/_sticky_header_dispensary.html.erb
<!--product categories-->
<div class="row" style="margin-top: 20px;">
	<h3 align="center">Dispensary Products</h3>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="section-title">
            <% @category_to_products.each_with_index  do |(key, list), index| %>
                
                <% if index == 0 %>
                    <h2 class="h6 inline-block uppercase header-button active-header-button <%=key%>-button" 
                        onClick="changeProductCategory('<%=key%>')"><%= key %></h2>
                <% else %>
                    <h2 class="h6 inline-block uppercase header-button inactive-header-button <%=key%>-button" 
                        onClick="changeProductCategory('<%=key%>')"><%= key %></h2>
                <% end %>

            <% end %>
        </div>
    </div>
</div>

app/views/shared/_sticky_header_home.html.erb
<form action="#">
    <h3 align="center" style="margin-top: 10px; margin-bottom: -5px;">What Are You Looking For?</h3>
    <div class="sing-option zm-trending">
        <select name="Category" class="selectDropdown" data-live-search="true" onChange="window.location.href=this.value">
            <option value = "<%= root_path %>">News</option>
            <% @news_categories.each do |category| %>
                
                <% if @category != nil && @category.name == category.name %>
                    <option value = "<%=category_path(category)%>" selected="selected"><%=category.name%></option>
                <% else %>
                    <option value = "<%=category_path(category)%>"><%=category.name%></option>
                <% end %>
                
        	<% end %>
        </select>
    </div>
    <div class="sing-option zm-state">
        <select name="State" class="selectDropdown" data-live-search="true" onChange="window.location.href=this.value">
        	<option value = "<%= root_path %>">States</option>
        	<% @all_states.each do |state| %>
        	
        	    <% if @state != nil && @state.name == state.name %>
                    <option value = "<%=state_path(state)%>" selected="selected"><%=state.name%></option>
                <% else %>
                    <option value = "<%=state_path(state)%>"><%=state.name%></option>
                <% end %>
    
        	<% end %>
        </select>
    </div>
    <div class="sing-option zm-state">
        <select name="Source" class="selectDropdown" data-live-search="true" onChange="window.location.href=this.value">
            <option value = "<%= root_path %>">Products</option>
            <% @product_categories.each do |category| %>
                
                <option value = "<%=products_path(category.name)%>"><%=category.name%></option>
    
                <% if category.name == 'Flower' %>
                    <option value="<%=products_path('Indica')%>">&nbsp&nbsp&nbsp&nbspIndica</option>
                    <option value="<%=products_path('Sativa')%>">&nbsp&nbsp&nbsp&nbspSativa</option>
                    <option value="<%=products_path('Hybrid')%>">&nbsp&nbsp&nbsp&nbspHybrid</option>
                    <option value="<%=products_path('Hybrid-Indica')%>">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspHybrid-Indica</option>
                    <option value="<%=products_path('Hybrid-Sativa')%>">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspHybrid-Sativa</option>
                <% end %>
                
        	<% end %>
        </select>
    </div>
</form>

app/views/shared/_sticky_header_news.html.erb
<form action="#">
    <h3 align="center" style="margin-top: 10px; margin-bottom: -5px;">Refine News</h3>
    <div class="sing-option zm-trending">
        <select name="Category" class="selectDropdown" data-live-search="true" onChange="window.location.href=this.value">
            <option value = "<%= root_path %>">Category</option>
            <% @news_categories.each do |category| %>
                
                <% if @category != nil && @category.name == category.name %>
                    <option value = "<%=category_path(category)%>" selected="selected"><%=category.name%></option>
                <% else %>
                    <option value = "<%=category_path(category)%>"><%=category.name%></option>
                <% end %>
                
        	<% end %>
        </select>
    </div>
    <div class="sing-option zm-state">
        <select name="State" class="selectDropdown" data-live-search="true" onChange="window.location.href=this.value">
        	<option value = "<%= root_path %>">State</option>
        	<% @all_states.each do |state| %>
        	
        	    <% if @state != nil && @state.name == state.name %>
                    <option value = "<%=state_path(state)%>" selected="selected"><%=state.name%></option>
                <% else %>
                    <option value = "<%=state_path(state)%>"><%=state.name%></option>
                <% end %>
    
        	<% end %>
        </select>
    </div>
    <div class="sing-option zm-state">
        <select name="Source" class="selectDropdown" data-live-search="true" onChange="window.location.href=this.value">
            <option value = "<%= root_path %>">Source</option>
            <% @active_sources.each do |source| %>
            
                <% if @source != nil && @source.name == source.name %>
                    <option value = "<%=source_path(source)%>" selected="selected"><%=source.name%></option>
                <% else %>
                    <option value = "<%=source_path(source)%>"><%=source.name%></option>
                <% end %>
    
        	<% end %>
        </select>
    </div>
</form>

app/views/shared/_sticky_header_products.html.erb
<%= form_tag products_refine_index_path do %>
	<h3 align="center" style="margin-top: 10px; margin-bottom: -5px;">Refine Products</h3>	
	<div class="sing-option zm-trending">  
        <%= render 'shared/dropdown_states' %>
    </div>
    
    <div class="sing-option zm-state"> 
        <%= render 'shared/dropdown_categories' %>
    </div>
    
    <div class="sing-option zm-state"> 
        <%= render 'shared/dropdown_az' %>
    </div>
    
    <div class = "product-refine-buttons">
    	<!--hidden values-->
    	<input type = "hidden" id="state_search" name = "state_search"/>
    	<input type = "hidden" id="category_search" name = "category_search"/>
    	<input type = "hidden" id="az_search" name = "az_search"/>
    	
    	<div class="btn-group btn-group-justified">
            <button type="submit" class="button" 
                    style="width: 50%; margin-bottom: 0px; margin: 10px 0px; border-right: 1px solid black">Refine Results</button>
        
            <button type="button" class="button" onclick="clearFormValues();"
                	style="width: 50%; margin-bottom: 0px; margin: 10px 0px;">Clear Filters</button>
        </div>
    </div>
<% end %>