config/routes.rb
Rails.application.routes.draw do

  #active admin
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  match "/admin/admin_users/import_admin_users" => 'admin/admin_users#import_admin_users', via: [:get, :post]
  match "/admin/articles/import_articles" => 'admin/articles#import_articles', via: [:get, :post]
  match "/admin/average_prices/import_average_prices" => 'admin/average_prices#import_average_prices', via: [:get, :post]
  match "/admin/categories/import_categories" => 'admin/categories#import_categories', via: [:get, :post]
  match "/admin/dispensaries/import_dispensaries" => 'admin/dispensaries#import_dispensaries', via: [:get, :post]
  match "/admin/products/import_products" => 'admin/products#import_products', via: [:get, :post]
  
  match "/admin/dispensary_sources/:id/add_to_store" => 'admin/dispensary_sources#add_to_store', via: :post
  match "/admin/dispensary_sources/:id/delete_from_store" => 'admin/dispensary_sources#delete_from_store', via: :post
  match "/admin/dispensary_sources/:id/update_product_store" => 'admin/dispensary_sources#update_product_store', via: :put
  match "/admin/dispensary_source_products/add_to_store" => 'admin/dispensary_source_products#add_to_store', via: :post
  match "/admin/dispensary_products/add_to_store" => 'admin/dispensary_products#add_to_store', via: [:post, :patch]
  
  #ecommerce
  resources :carts
  resources :product_items
  get 'add_to_cart/:product_id/:dispensary_source_id', to: 'product_items#add_to_cart', :as => :add_to_cart
  resources :orders
  
  #SIDEKIQ Routes
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => "/background"

  #GENERAL PAGES
  root 'pages#home'

  get 'admin', to: 'pages#admin'
  get 'search', to: 'pages#search'
  get 'save_email', to: 'pages#save_email'
  get 'unsubscribe', to: 'pages#unsubscribe'
  
  get 'contact_us', to: 'pages#contact_us'
  get 'submit_contact_form', to: 'pages#submit_contact_form'
  
  get 'feedback', to: 'pages#feedback'
  get 'submit_feedback_form', to: 'pages#submit_feedback_form'
  
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms_conditions', to: 'pages#terms_conditions'
  get 'about', to: 'pages#about'
  
  #sitemap
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  
  #DIFF STYLING
  get 'test', to: 'diff_layouts#test'
  
  #LOGIN AND LOGOUT
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #USER
  get 'signup', to: 'users#new'
  resources :users, except: [:new] do 
    collection do
      delete 'destroy_multiple'
    end
  end
  get 'users-admin', to: 'users#admin'
  get 'change_password/:id', to: 'users#change_password', as: 'change_password'
  get 'submit_password_change', to: 'users#submit_password_change' 
  
  put 'user_source_save/:source_id', to: 'users#user_source_save', as: 'user_source_save'
  put 'user_category_save/:category_id', to: 'users#user_category_save', as: 'user_category_save'
  put 'user_state_save/:state_id', to: 'users#user_state_save', as: 'user_state_save'
  
  #RESET PASSWORD
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  #ERROR FILES
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'errors/application_error'
  
  #ERROR HANDLING
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/503", :to => "errors#application_error", :via => :all
  
  resources :blog
  resources :categories
  resources :sources
  resources :average_prices
  resources :vendor_products
  resources :dispensary_sources
  resources :dispensary_source_products
  resources :dsp_prices
  resources :dispensary_products

  #ARTICLES
  resources :articles
  get 'digest', to: 'articles#digest'
  get 'send_weekly_digest', to: 'articles#send_weekly_digest'
  get 'tweet/:id', to: 'articles#tweet', as: 'tweet'
  put 'save_visit/:id', to: 'articles#save_visit', as: 'save_visit'
  put 'user_article_save/:id', to: 'articles#user_article_save', as: 'user_article_save'
  get 'send_tweet', to: 'articles#send_tweet'
  get 'update_states_categories', to: 'articles#update_states_categories'
  get 'update_article_tags', to: 'articles#update_article_tags'
  
  #PRODUCTS
  resources :products
  post "products_refine_index", to: "products#refine_index"
  get "products_refine_index", to: "products#refine_index"
  post 'products/:id/change_state' => 'products#change_state', as: 'change_state_product'
  
  #STATES
  resources :states
  post 'states/:id/refine_products' => 'states#refine_products', as: 'refine_state_products'

  #VENDORS
  resources :vendors
  post 'vendors/refine_index' => 'vendors#refine_index', as: 'refine_vendor_index'

  #DISPENSARIES
  resources :dispensaries
  post 'dispensaries/refine_index' => 'dispensaries#refine_index', as: 'refine_dispensary_index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	
	has_many :product_items, dependent: :destroy
	
	# def add_product(product_id, dispensary_source_id, dsp_price_id, quantity)

	# 	#see if this item is currently in this cart
	# 	current_items = product_items.where(product_id: product_id).
	# 						where(dispensary_source_id: dispensary_source_id).where(dsp_price_id: dsp_price_id)
							
	# 	current_item = nil
	# 	if current_items.size > 0
	# 		#if item in cart, add to quantity
	# 		current_item = current_items[0]
	# 		current_item.quantity += quantity
	# 	else
	# 		current_item = product_items.build(product_id: product_id, 
	# 							dispensary_source_id: dispensary_source_id, dsp_price_id: dsp_price_id, quantity: quantity)
	# 	end
	# 	current_item
	# end
	
	def total_price
		product_items.to_a.sum{|item| item.total_price}
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	
	before_action :set_cart, only: [:show, :destroy]
	rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
	
	def new
		@cart = Cart.new
	end
	
	def show
	end
	
	def destroy
		# @cart.destroy if @cart.id == session[:cart_id]
		# redirect_to root_path, notice: 'Your Cart is Empty'
	end
	
	private 
	
	def set_cart 
		@cart = Cart.find(params[:id])
	end
	
	def cart_params
		params[:cart]
	end
	
	def invalid_cart
		# logger_error = 'You are trying to access an invalid cart'
		redirect_to root_path, notice: 'Invalid Cart'
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="cart-line-items" class="tab-content" style="display: block;">
    <div class = 'ajax-spinner'>
        <%= image_tag("icons/ajax-loader.gif") %>
    </div>
	<table data-role="table" data-mode="columntoggle" class="ui-responsive" id="myTable" style="width: 100%;">
		<thead>
			<tr>
				<th>Product</th>
				<th>Dispensary</th>
				<th>Quantity</th>
				<th>Unit</th>
				<th>Price</th>
				<th data-priority="1" class="delbtn">Remove Item</th>
			</tr>
		</thead>
		<tbody>
			<!--loop through saved articles and add to row-->
			<% @cart.product_items.each do |item| %>
				<tr>
				    
					<td style="padding: 4px 4px; border-bottom: 1px solid #7c8c99">
					    <%=link_to item.product.name, product_path(item.product)%>
					</td>
					<td style="padding: 4px 4px; border-bottom: 1px solid #7c8c99">
					    <%=item.dispensary_source.name %>
				    </td>
				    <td style="padding: 4px 4px; border-bottom: 1px solid #7c8c99">
					    <%=item.quantity %>
				    </td>
				    <td style="padding: 4px 4px; border-bottom: 1px solid #7c8c99">
					    <%=item.dsp_price.unit %>
				    </td>
				    <td style="padding: 4px 4px; border-bottom: 1px solid #7c8c99">
					    <%= number_to_currency item.total_price %>
				    </td>
					<td class="delbtn" style="padding: 4px 4px; border-bottom: 1px solid #7c8c99">
						<span class="btn btn-default btn-sm">
						    <%= link_to "Remove", product_item_path(item), method: :delete,
		                      data: { confirm: "Remove Item From Cart?"},
		                      class: "btn" %>
						</span>
					</td>          
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/carts/_old_cart.html.erb
<% @cart.product_items.each do |item| %>
  <ul>
	  <li>
	    <%= item.quantity %> <%=item.dsp_price.unit%> of <%= item.product.name %> from <%=item.dispensary_source.name %>
	    <%= number_to_currency item.total_price %>
	  </li>
  </ul>
<% end %>

app/views/carts/show.html.erb
<!-- Start page content -->
<section id="page-content" class="page-wrapper">
    <!-- Start contact message area -->
    <div class="zm-section bg-white pt-60">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-12">
                    <div class="section-title-2 mb-40  text-center">
                        <h3 class="inline-block uppercase">Shopping Cart</h3>
                    </div>
                </div>
            </div>
            <div class="message-box">
                
                <% if @cart.product_items.any? %>
                    <div style = "float: right; margin-right: 20px;">
                        <%= link_to "Empty Your Cart", cart_path(@cart), method: :delete,
    		                  data: { confirm: "Are you sure you want to empty your cart?"},
    		                  class: "btn" %>
                    </div>
                    <%= render 'carts/cart' %>
                    <div style = "float: right; margin: 20px 20px 0 0;">
                        <h5 style = "margin-botton: 10px;">Total: <%= number_to_currency @cart.total_price %> </h5>
                        <%= button_to 'Checkout', new_order_path, method: :get %>
                    </div>
                    
                <% else %>
                    <p>No Items In Cart</p>
                <% end %>

            </div>
        </div>
    </div>
</section>
<!-- End page content -->