config/routes.rb
Rails.application.routes.draw do

  #active admin
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  match "/admin/admin_users/import_admin_users" => 'admin/admin_users#import_admin_users', via: [:get, :post]
  match "/admin/articles/import_articles" => 'admin/articles#import_articles', via: [:get, :post]
  match "/admin/average_prices/import_average_prices" => 'admin/average_prices#import_average_prices', via: [:get, :post]
  match "/admin/categories/import_categories" => 'admin/categories#import_categories', via: [:get, :post]
  match "/admin/dispensaries/import_dispensaries" => 'admin/dispensaries#import_dispensaries', via: [:get, :post]
  match "/admin/products/import_products" => 'admin/products#import_products', via: [:get, :post]
  
  match "/admin/dispensary_sources/:id/add_to_store" => 'admin/dispensary_sources#add_to_store', via: :post
  match "/admin/dispensary_sources/:id/delete_from_store" => 'admin/dispensary_sources#delete_from_store', via: :post
  match "/admin/dispensary_sources/:id/update_product_store" => 'admin/dispensary_sources#update_product_store', via: :put
  match "/admin/dispensary_source_products/add_to_store" => 'admin/dispensary_source_products#add_to_store', via: :post
  match "/admin/dispensary_products/add_to_store" => 'admin/dispensary_products#add_to_store', via: [:post, :patch]
  
  #ecommerce
  resources :carts
  resources :product_items
  get 'add_to_cart/:product_id/:dispensary_source_id', to: 'product_items#add_to_cart', :as => :add_to_cart
  resources :orders
  
  #SIDEKIQ Routes
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => "/background"

  #GENERAL PAGES
  root 'pages#home'

  get 'admin', to: 'pages#admin'
  get 'search', to: 'pages#search'
  get 'save_email', to: 'pages#save_email'
  get 'unsubscribe', to: 'pages#unsubscribe'
  
  get 'contact_us', to: 'pages#contact_us'
  get 'submit_contact_form', to: 'pages#submit_contact_form'
  
  get 'feedback', to: 'pages#feedback'
  get 'submit_feedback_form', to: 'pages#submit_feedback_form'
  
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms_conditions', to: 'pages#terms_conditions'
  get 'about', to: 'pages#about'
  
  #sitemap
  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  
  #DIFF STYLING
  get 'test', to: 'diff_layouts#test'
  
  #LOGIN AND LOGOUT
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #USER
  get 'signup', to: 'users#new'
  resources :users, except: [:new] do 
    collection do
      delete 'destroy_multiple'
    end
  end
  get 'users-admin', to: 'users#admin'
  get 'change_password/:id', to: 'users#change_password', as: 'change_password'
  get 'submit_password_change', to: 'users#submit_password_change' 
  
  put 'user_source_save/:source_id', to: 'users#user_source_save', as: 'user_source_save'
  put 'user_category_save/:category_id', to: 'users#user_category_save', as: 'user_category_save'
  put 'user_state_save/:state_id', to: 'users#user_state_save', as: 'user_state_save'
  
  #RESET PASSWORD
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  #ERROR FILES
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'errors/application_error'
  
  #ERROR HANDLING
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  match "/503", :to => "errors#application_error", :via => :all
  
  resources :blog
  resources :categories
  resources :sources
  resources :average_prices
  resources :vendor_products
  resources :dispensary_sources
  resources :dispensary_source_products
  resources :dsp_prices
  resources :dispensary_products

  #ARTICLES
  resources :articles
  get 'digest', to: 'articles#digest'
  get 'send_weekly_digest', to: 'articles#send_weekly_digest'
  get 'tweet/:id', to: 'articles#tweet', as: 'tweet'
  put 'save_visit/:id', to: 'articles#save_visit', as: 'save_visit'
  put 'user_article_save/:id', to: 'articles#user_article_save', as: 'user_article_save'
  get 'send_tweet', to: 'articles#send_tweet'
  get 'update_states_categories', to: 'articles#update_states_categories'
  get 'update_article_tags', to: 'articles#update_article_tags'
  
  #PRODUCTS
  resources :products
  post "products_refine_index", to: "products#refine_index"
  get "products_refine_index", to: "products#refine_index"
  post 'products/:id/change_state' => 'products#change_state', as: 'change_state_product'
  
  #STATES
  resources :states
  post 'states/:id/refine_products' => 'states#refine_products', as: 'refine_state_products'

  #VENDORS
  resources :vendors
  post 'vendors/refine_index' => 'vendors#refine_index', as: 'refine_vendor_index'

  #DISPENSARIES
  resources :dispensaries
  post 'dispensaries/refine_index' => 'dispensaries#refine_index', as: 'refine_dispensary_index'

end

app/models/dispensary_source_product.rb
class DispensarySourceProduct < ActiveRecord::Base
    
    #scope
    scope :for_featured, -> { 
        product_ids = Product.where(:featured_product => true).pluck(:id)
        where("product_id IN (?)", product_ids)
    }
    
    #relations
    belongs_to :product, counter_cache: :dsp_count
    belongs_to :dispensary_source
    has_many :dsp_prices
    accepts_nested_attributes_for :dsp_prices, allow_destroy: true
    
    #validations
    validates :dispensary_source_id, presence: true
    validates_uniqueness_of :product_id, :scope => :dispensary_source_id #no duplicate products per dispensary
    
    #delete related DSPPrices
    before_destroy :delete_dsp_prices
    def delete_dsp_prices
       self.dsp_prices.destroy_all 
    end
end

app/views/admin/dispensary_source_products/_dispensary_products.html.erb
<% dispensary_source_products =  current_admin_user.dispensary_source.dispensary_source_products %>
<% dispensary_source = current_admin_user.dispensary_source %>  
  <% if current_admin_user.dispensary_admin_user? %>
    <div class="tab">
      <button class="tablinks active" id="tab1">Your Product</button>
      <button class="tablinks" id="tab2">Available Product</button>
    </div>
    <!-- Tab content -->
    <div id="yourProduct" class="tabcontent" >
     <% if dispensary_source_products.any? %>
        <h3>Your Products</h3>
        <%= render partial: 'dispensary_source_products', 
          locals: {dispensary_source_products: dispensary_source_products} %>
        <% else %>
          <p>You are not currently selling any products on here. Add some below</p>
        <% end %>
    </div>
    <div id="availableProduct" class="tabcontent" style="display: none;">
      <h3>Available Products</h3>
      <%= render partial: 'products', locals: {products: Product.featured} %>
    </div>
  <% end %>


<!--javascript needed for price popup-->
<script type="text/javascript">
    
    $(document).ready(function(){
        // Add selling price 
        $(document).on('click', ".add_to_store", function(){
            product_id = $(this).attr('product_id')
            ds_id = "<%=@dispensary_source.id %>";
            ActiveAdmin.modal_dialog("Enter Selling Price", {price: 'number'}, function(inputs) {
                $.ajax({
                    type: "POST",
                    url: "/admin/dispensary_sources/" + ds_id +"/add_to_store",
                    data: {
                        product_id: product_id,
                        price: $("input[name='price']").last().val()
                    },
                    success: function(data) {
                        window.location.reload()
                        return false;
                    },
                    error: function(data) {
                        return false;
                    }
                });
            });
        });

        // $("#tab1").click(function(){
        //   $("#yourProduct").show();
        //   $("#availableProduct").hide();
        //   $("#tab2").removeClass('active')
        //   $("#tab1").addClass('active')
        // });
        // $("#tab2").click(function(){
        //   $("#tab2").addClass('active');
        //   $("#tab1").removeClass('active');
        //   $("#yourProduct").hide();
        //   $("#availableProduct").show();
        // });


       
    });
</script>

app/views/admin/dispensary_source_products/_index.html.erb
<div class="tab">
  <button class="tablinks active" id="tab1">Your Product</button>
  <button class="tablinks" id="tab2">Available Product</button>
</div>
<div id="yourProduct">
  <div>
    <h3>Your Products</h3>
    <table border="0" cellspacing="0" cellpadding="0" id="dispensary_source_products" class="index_table index" paginator="true">
      <thead>
        <tr>
          <th class="col col-customer">Name</th>
          <th class="col col-actions">Action</th>
        </tr>
      </thead>
      <tbody>
        <% index_count = 0 %>
        <% @dispensary_source_products.each do |dsp| %>
        <tr class="<%= ((index_count % 2) == 0) ? 'even' : 'odd' %>" id="dispensary_source_order_1">
          <td class="col col-customer"><%=dsp.product.name %></td>
          <td class="col col-actions">
             <%= link_to "View",admin_dispensary_product_path(dsp), class: "remove", method: :get %>
          </td>
        </tr>
        <% index_count += 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div id="availableProduct" class="tabcontent" style="display: none;">
  <h3>Available Products</h3>
    <table border="0" cellspacing="0" cellpadding="0" id="index_table_stores" class="index_table index" paginator="true">
    <thead>
        <tr>
            <th class="sortable col-name">Name</th>
            <th class="col col-actions">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% index_count = 0 %>
        <% @products.each do |product| %>
            <tr class="<%= ((index_count % 2) == 0) ? 'even' : 'odd' %>">
                <td class="col"><%=product.name %></td>
                <td class="col col-actions">
                    <%= link_to "Add to Store", new_admin_dispensary_product_path(product_id: product.id), 
                            class: "add_to_store", method: :get %>  
                </td>
            </tr>
            <% index_count += 1 %>
        <% end %>
    </tbody>
  </table>
</div>
<script type="text/javascript">
  $(document).ready(function(){
      // Add selling price 
      $("#tab1").click(function(){
        $("#yourProduct").show();
        $('#dispensary_source_products').show();
        $("#availableProduct").hide();
        $("#tab2").removeClass('active')
        $("#tab1").addClass('active')
     });
      $("#tab2").click(function(){
        $("#tab2").addClass('active')
        $("#tab1").removeClass('active')
        $("#yourProduct").hide();
        $('#dispensary_source_products').hide();
        $('#availableProduct').show();
      });
  });

 
</script> 

app/views/admin/dispensary_source_products/_products.html.erb
<table border="0" cellspacing="0" cellpadding="0" id="index_table_stores" class="index_table index" paginator="true">
  <thead>
    <tr>
      <th class="sortable col-name">Name</th>
      <th class="col col-actions">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% index_count = 0 %>
    <% products.each do |product| %>
      <tr class="<%= ((index_count % 2) == 0) ? 'even' : 'odd' %>">
        <td class="col"><%=product.name %></td>
        <td class="col col-actions">
          <%= link_to "Add to Store", "javascript:void(0)", product_id: product.id, class: "add_to_store", method: :post %>
        </td>
      </tr>
      <% index_count += 1 %>
    <% end %>
  </tbody>
</table>